const modelData = {
                        user: [{
                                "id":1,
                                "name":"test1",
                                "age": 11,
                                "gender":"male",
                                "email":"test1@gmail.com",
                                "phoneNo":"9415346313"
                        },
                        {
                                "id":2,
                                "name":"test2",
                                "age":"11",
                                "gender":"female",
                                "email":"test1@gmail.com",
                                "phoneNo":"9415346314"
                        },
                        {
                                "id":3,
                                "name":"test3",
                                "age":"11",
                                "gender":"female",
                                "email":"test1@gmail.com",
                                "phoneNo":"9415346315"
                        },
                        {
                                "id":4,
                                "name":"test4",
                                "age":"11",
                                "gender":"female",
                                "email":"test1@gmail.com",
                                "phoneNo":"9415346316"
                        },
                        {
                                "id":5,
                                "name":"test5",
                                "age":"11",
                                "gender":"male",
                                "email":"test1@gmail.com",
                                "phoneNo":"9415346317"
                        },
                        {
                                "id":6,
                                "name":"test6",
                                "age":"11",
                                "gender":"male",
                                "email":"test1@gmail.com",
                                "phoneNo":"9415346318"
                        },
                    ]
}
export default modelData;